Repository red-hat-data-services/odh-deployer, pull requests merged in 2022-10, with the labels that each got.

#261 Remove explicit CUDA version from imagestreamtag
  nbc/cuda-11.4.2/manifests.yaml
Labels: lgtm, approved

#262 Remove deletion of CRO resources
  deploy.sh
Labels: lgtm, approved

#263 Fix RHODS Jupyter Probe Success Burn Rate
  deploy.sh
  monitoring/prometheus/prometheus-configs.yaml
Labels: lgtm, approved

#260 ISV CRS, CRD and on prem apps 4907
  deploy.sh
  odh-dashboard/apps-managed-service/kustomization.yaml
  odh-dashboard/apps-managed-service/nvidia/gpu-enabled-notebook-quickstart.yaml
  odh-dashboard/apps-managed-service/nvidia/gpu-quickstart.yaml
  odh-dashboard/apps-managed-service/nvidia/kustomization.yaml
  odh-dashboard/apps-managed-service/nvidia/nvidia-app.yaml
  odh-dashboard/apps-managed-service/rhoam/deploy-model-rhoam-quickstart.yaml
  odh-dashboard/apps-managed-service/rhoam/kustomization.yaml
  odh-dashboard/apps-managed-service/rhoam/rhoam-app.yaml
  odh-dashboard/apps-managed-service/starburst/kustomization.yaml
  odh-dashboard/apps-managed-service/starburst/starburst-app.yaml
  odh-dashboard/apps-managed-service/starburst/starburst-galaxy-quickstart.yaml
  odh-dashboard/apps-on-prem/aikit/aikit-app.yaml
  odh-dashboard/apps-on-prem/aikit/kustomization.yaml
  odh-dashboard/apps-on-prem/aikit/oneapi-aikit-notebook-quickstart.yaml
  odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-app.yaml
  odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-create-jupyter-notebook-quickstart.yaml
  odh-dashboard/apps-on-prem/anaconda-ce/anaconda-ce-docs.yaml
  odh-dashboard/apps-on-prem/anaconda-ce/kustomization.yaml
  odh-dashboard/apps-on-prem/jupyter/create-jupyter-notebook-quickstart.yaml
  odh-dashboard/apps-on-prem/jupyter/deploy-python-model-quickstart.yaml
  odh-dashboard/apps-on-prem/jupyter/jupyter-app.yaml
  odh-dashboard/apps-on-prem/jupyter/jupyter-docs.yaml
  odh-dashboard/apps-on-prem/jupyter/jupyterhub-app.yaml
  odh-dashboard/apps-on-prem/jupyter/kustomization.yaml
  odh-dashboard/apps-on-prem/kustomization.yaml
  odh-dashboard/apps-on-prem/openvino/kustomization.yaml
  odh-dashboard/apps-on-prem/openvino/openvino-app.yaml
  odh-dashboard/apps-on-prem/openvino/openvino-docs.yaml
  odh-dashboard/apps-on-prem/openvino/openvino-inference-notebook.yaml
  odh-dashboard/apps-on-prem/pachyderm/kustomization.yaml
  odh-dashboard/apps-on-prem/pachyderm/pachyderm-app.yaml
  odh-dashboard/apps-on-prem/pachyderm/pachyderm-beginner-tutorial-notebook.yaml
  odh-dashboard/apps-on-prem/pachyderm/pachyderm-docs.yaml
  odh-dashboard/apps-on-prem/rhosak/connect-rhosak-notebook-quickstart.yaml
  odh-dashboard/apps-on-prem/rhosak/kustomization.yaml
  odh-dashboard/apps-on-prem/rhosak/rhosak-app.yaml
  odh-dashboard/apps-on-prem/seldon/kustomization.yaml
  odh-dashboard/apps-on-prem/seldon/seldon-app.yaml
  odh-dashboard/apps-on-prem/seldon/seldon-deploy-canary-quickstart.yaml
  odh-dashboard/apps-on-prem/seldon/seldon-deploy-drift-quickstart.yaml
  odh-dashboard/apps-on-prem/seldon/seldon-deploy-explainer-quickstart.yaml
  odh-dashboard/apps-on-prem/seldon/seldon-deploy-outlier-quickstart.yaml
  odh-dashboard/apps-on-prem/seldon/seldon-docs.yaml
  odh-dashboard/apps-on-prem/watson/deploy-watson-model-quickstart.yaml
  odh-dashboard/apps-on-prem/watson/kustomization.yaml
  odh-dashboard/apps-on-prem/watson/watson-docs.yaml
  odh-dashboard/apps-on-prem/watson/watson-studio-app.yaml
  odh-dashboard/configs/odh-dashboard-config.yaml
  odh-dashboard/crds/kustomization.yaml
  odh-dashboard/crds/odh-application-crd.yaml
  odh-dashboard/crds/odh-dashboard-crd.yaml
  odh-dashboard/crds/odh-document-crd.yaml
  odh-dashboard/crds/odh-quick-start-crd.yaml
Labels: approved

#268 Do not delete CRO cluster scope resources
  deploy.sh
Labels: lgtm

#269 Add livenessProbe fix to patch dashboard deployment on 1.17 upgrade
  deploy.sh
Labels: lgtm
