Repository red-hat-data-services/odh-deployer, pull requests merged in 2023-01, with the labels that each got.

#295 Update Prometheus ubi8-minimal images
  deploy.sh
  monitoring/prometheus/blackbox-exporter-common.yaml
  monitoring/prometheus/prometheus.yaml
Labels: lgtm

#297 Merge pull request #295 from red-hat-data-services/update_wait_contai…
  deploy.sh
  monitoring/prometheus/blackbox-exporter-common.yaml
  monitoring/prometheus/prometheus.yaml
Labels: lgtm, approved

#299 Fix Security policies for prometheus container
  monitoring/prometheus/prometheus.yaml
Labels: lgtm, approved

#302 Update Serving Runtime Config
  deploy.sh
  model-mesh/serving_runtime_config.yaml
Labels: lgtm

#301 Update Serving Runtime Config
  deploy.sh
  model-mesh/serving_runtime_config.yaml
Labels: lgtm, approved, qe-approved
