Repository red-hat-data-services/odh-deployer, pull requests merged in 2023-06, with the labels that each got.

#340 Update servingruntime ootb configuration
  odh-dashboard/modelserving/kustomization.yaml
  odh-dashboard/modelserving/ovms-gpu-ootb.yaml
  odh-dashboard/modelserving/ovms-ootb.yaml
Labels: lgtm, approved, qe-approved

#344 Fix issue deploying starbust
  odh-dashboard/apps-on-prem/kustomization.yaml
Labels: lgtm, approved, qe-approved

#352 Modify Approver List
  CONTRIBUTING.md
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, qe-approved

#353 Add zdtsw as appover and fix sorting
  OWNERS_ALIASES
Labels: lgtm, approved

#358 Fix isv rearrange order
  odh-dashboard/apps-managed-service/kustomization.yaml
  odh-dashboard/apps-managed-service/nvidia/gpu-enabled-notebook-quickstart.yaml
  odh-dashboard/apps-managed-service/nvidia/gpu-quickstart.yaml
  odh-dashboard/apps-managed-service/nvidia/kustomization.yaml
  odh-dashboard/apps-managed-service/nvidia/nvidia-app.yaml
  odh-dashboard/apps-managed-service/rhoam/deploy-model-rhoam-quickstart.yaml
  odh-dashboard/apps-managed-service/rhoam/kustomization.yaml
  odh-dashboard/apps-managed-service/rhoam/rhoam-app.yaml
  odh-dashboard/apps-on-prem/kustomization.yaml
  odh-dashboard/apps/aikit/aikit-app.yaml
  odh-dashboard/apps/aikit/kustomization.yaml
  odh-dashboard/apps/aikit/oneapi-aikit-notebook-quickstart.yaml
  odh-dashboard/apps/anaconda-ce/anaconda-ce-app.yaml
  odh-dashboard/apps/anaconda-ce/anaconda-ce-create-jupyter-notebook-quickstart.yaml
  odh-dashboard/apps/anaconda-ce/anaconda-ce-docs.yaml
  odh-dashboard/apps/anaconda-ce/kustomization.yaml
  odh-dashboard/apps/jupyter/create-jupyter-notebook-quickstart.yaml
  odh-dashboard/apps/jupyter/deploy-python-model-quickstart.yaml
  odh-dashboard/apps/jupyter/jupyter-app.yaml
  odh-dashboard/apps/jupyter/jupyter-docs.yaml
  odh-dashboard/apps/jupyter/jupyterhub-app.yaml
  odh-dashboard/apps/jupyter/kustomization.yaml
  odh-dashboard/apps/kustomization.yaml
  odh-dashboard/apps/openvino/kustomization.yaml
  odh-dashboard/apps/openvino/openvino-app.yaml
  odh-dashboard/apps/openvino/openvino-docs.yaml
  odh-dashboard/apps/openvino/openvino-inference-notebook.yaml
  odh-dashboard/apps/pachyderm/kustomization.yaml
  odh-dashboard/apps/pachyderm/pachyderm-app.yaml
  odh-dashboard/apps/pachyderm/pachyderm-beginner-tutorial-notebook.yaml
  odh-dashboard/apps/pachyderm/pachyderm-docs.yaml
  odh-dashboard/apps/watson/deploy-watson-model-quickstart.yaml
  odh-dashboard/apps/watson/kustomization.yaml
  odh-dashboard/apps/watson/watson-docs.yaml
  odh-dashboard/apps/watson/watson-studio-app.yaml
Labels: lgtm, approved

#359 Fix isv rearrange order
  odh-dashboard/apps-managed-service/kustomization.yaml
  odh-dashboard/apps-managed-service/nvidia/gpu-enabled-notebook-quickstart.yaml
  odh-dashboard/apps-managed-service/nvidia/gpu-quickstart.yaml
  odh-dashboard/apps-managed-service/nvidia/kustomization.yaml
  odh-dashboard/apps-managed-service/nvidia/nvidia-app.yaml
  odh-dashboard/apps-managed-service/rhoam/deploy-model-rhoam-quickstart.yaml
  odh-dashboard/apps-managed-service/rhoam/kustomization.yaml
  odh-dashboard/apps-managed-service/rhoam/rhoam-app.yaml
  odh-dashboard/apps-on-prem/kustomization.yaml
  odh-dashboard/apps/aikit/aikit-app.yaml
  odh-dashboard/apps/aikit/kustomization.yaml
  odh-dashboard/apps/aikit/oneapi-aikit-notebook-quickstart.yaml
  odh-dashboard/apps/anaconda-ce/anaconda-ce-app.yaml
  odh-dashboard/apps/anaconda-ce/anaconda-ce-create-jupyter-notebook-quickstart.yaml
  odh-dashboard/apps/anaconda-ce/anaconda-ce-docs.yaml
  odh-dashboard/apps/anaconda-ce/kustomization.yaml
  odh-dashboard/apps/jupyter/create-jupyter-notebook-quickstart.yaml
  odh-dashboard/apps/jupyter/deploy-python-model-quickstart.yaml
  odh-dashboard/apps/jupyter/jupyter-app.yaml
  odh-dashboard/apps/jupyter/jupyter-docs.yaml
  odh-dashboard/apps/jupyter/jupyterhub-app.yaml
  odh-dashboard/apps/jupyter/kustomization.yaml
  odh-dashboard/apps/kustomization.yaml
  odh-dashboard/apps/openvino/kustomization.yaml
  odh-dashboard/apps/openvino/openvino-app.yaml
  odh-dashboard/apps/openvino/openvino-docs.yaml
  odh-dashboard/apps/openvino/openvino-inference-notebook.yaml
  odh-dashboard/apps/pachyderm/kustomization.yaml
  odh-dashboard/apps/pachyderm/pachyderm-app.yaml
  odh-dashboard/apps/pachyderm/pachyderm-beginner-tutorial-notebook.yaml
  odh-dashboard/apps/pachyderm/pachyderm-docs.yaml
  odh-dashboard/apps/watson/deploy-watson-model-quickstart.yaml
  odh-dashboard/apps/watson/kustomization.yaml
  odh-dashboard/apps/watson/watson-docs.yaml
  odh-dashboard/apps/watson/watson-studio-app.yaml
Labels: lgtm, approved

#360 Fix startbust enablement when installing operator
  odh-dashboard/apps-on-prem/starburst-enterprise/starburstenterprise-app.yaml
Labels: lgtm, approved

#361 Fix startbust enablement when installing operator
  odh-dashboard/apps-on-prem/starburst-enterprise/starburstenterprise-app.yaml
Labels: lgtm

#362 Update model-mesh kfdef
  kfdefs/rhods-model-mesh.yaml
Labels: lgtm
